services:
  fmb-app:
    image: ghcr.io/chernykh-dev/fmb-api
    ports:
      - "8080:8080" # Http
      - "8081:8081" # Https
    depends_on:
      fmb-db:
        condition: service_healthy
    env_file:
      - .env.test
    restart: always

  fmb-db:
    container_name: fmb-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data/fmb-db-data:rwx
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: ghcr.io/chernykh-dev/fmb-nginx
    ports:
      - "80:80"
    depends_on:
      - fmb-app
    restart: always
