services:
  fmb-app:
    build:
      context: ../FinanceManagerBackend.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Http
      - "8081:8081" # Https
    depends_on:
      fmb-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_HOST: "fmb-db"
      POSTGRES_DB: "fmb-db"
      POSTGRES_USER: "puser"
      POSTGRES_PASSWORD: "puserpass"

  fmb-db:
    container_name: fmb-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "fmb-db"
      POSTGRES_USER: "puser"
      POSTGRES_PASSWORD: "puserpass"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
